package no.nav.hjelpemidler.delbestilling.hjelpemidler

import no.nav.hjelpemidler.delbestilling.delbestilling.Del

val delerPerHjelpemiddel = mapOf(
    "Comet" to listOf(
        Del(
            "238403",
            "Hjul bak komplett",
            levArtNr = "SP1654383",
            kategori = "Hjul",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/238403.png",
        ),
        Del(
            "269827",
            "Hjul foran komplett",
            levArtNr = "SP1654351",
            kategori = "Hjul",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/269827.png",
        ),
        Del(
            "304570",
            "Batteri 12V 70-73,6 Ah C20 gele",
            levArtNr = "SPP50016",
            kategori = "Batteri",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/304570.png",
        ),
        Del(
            "249612",
            "Batterilader 10Ah",
            levArtNr = "SP1606544",
            kategori = "Lader",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/249612.jpg",
        ),
    ),
    "Orion" to listOf(
        Del(
            "304570",
            "Batteri 12V 70-73,6 Ah C20 gele",
            levArtNr = "SPP50016",
            kategori = "Batteri",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/304570.png",
        ),
        Del(
            "256635",
            "Hjul bak luft",
            levArtNr = null,
            kategori = "Hjul",
            maksAntall = 2,
        ),
        Del(
            "256634",
            "Hjul foran luft",
            levArtNr = "SP1608593",
            kategori = "Hjul",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/256634.png",
        ),
        Del(
            "249612",
            "Batterilader 10Ah",
            levArtNr = "SP1606544",
            kategori = "Lader",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/249612.jpg",
        ),
    ),
    "Minicrosser 125T" to listOf(
        Del(
            "200842",
            "Hjul 13x5.00-6 ",
            kategori = "Hjul",
            maksAntall = 4,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/200842.png",
        ),
        Del(
            "022005",
            "Batteri 80A inkl poler",
            kategori = "Batteri",
            maksAntall = 2,
        ),
        Del(
            "302543",
            "Batterilader 10Ah",
            kategori = "Lader",
            maksAntall = 2,
            levArtNr = "1523-1103",
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/302543.jpg",
        ),
    ),
    "Minicrosser M" to listOf(
        Del(
            "200842",
            "Hjul foran/bak",
            kategori = "Hjul",
            maksAntall = 4,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/200842.png",
        ),
        Del(
            "263773",
            "Batteri 85 ah",
            levArtNr = "1523-1138",
            kategori = "Batteri",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/263773.png",
        ),
        Del(
            "302543",
            "Batterilader 10Ah",
            kategori = "Lader",
            maksAntall = 2,
            levArtNr = "1523-1103",
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/302543.jpg",
        ),
    ),
    "Minicrosser X" to listOf(
        Del(
            "253277",
            "Hjul luft sommerhjul foran/bak",
            levArtNr = "1503-1003",
            kategori = "Hjul",
            maksAntall = 4,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/253277.jpg",
        ),
        Del(
            "291358",
            "Hjul punkteringsfri grovmønstret foran/bak",
            kategori = "Hjul",
            maksAntall = 4,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/291358.png",
        ),
        Del(
            "291356",
            "Hjul luft grovmønstret foran/bak",
            kategori = "Hjul",
            maksAntall = 4,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/291356.png",
        ),
        Del(
            "263773",
            "Batteri 85 ah",
            levArtNr = "1523-1138",
            kategori = "Batteri",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/263773.png",
        ),
        Del(
            "302543",
            "Batterilader 10Ah",
            kategori = "Lader",
            maksAntall = 2,
            levArtNr = "1523-1103",
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/302543.jpg",
        ),
    ),
    "Minicrosser T" to listOf(
        Del(
            "163943",
            "Hjul luft foran/bak",
            kategori = "Hjul",
            maksAntall = 4,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/163943.png",
        ),
        Del(
            "022005",
            "Batteri 80A inkl poler",
            kategori = "Batteri",
            maksAntall = 2,
        ),
        Del(
            "302543",
            "Batterilader 10Ah",
            kategori = "Lader",
            maksAntall = 2,
            levArtNr = "1523-1103",
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/302543.jpg",
        ),
    ),
    "Panthera" to listOf(
        Del(
            "150817",
            "Dekk Schwalbe Marathon Plus punkteringsbeskyttet 24\"x1",
            levArtNr = "1000038",
            kategori = "Dekk",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/150817.jpg",
        ),
        Del(
            "278247",
            "Slange 26\"",
            kategori = "Slange",
            maksAntall = 2,
        ),
        Del(
            "223382",
            "Svinghjul kompakt 5\"/120mm",
            kategori = "Svinghjul",
            maksAntall = 2,
        ),
        Del(
            "178498",
            "Dekk Schwalbe Marathon Plus punkteringsbeskyttet 26\"x1",
            levArtNr = "1000039",
            kategori = "Dekk",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/178498.jpg",
        ),
        Del(
            "184589",
            "Svinghjul X smal bane 86 mm",
            levArtNr = "2000061",
            kategori = "Svinghjul",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/184589.jpg",
        ),
        Del(
            "234334",
            "Svinghjul S3 Hjul120 mrs Panthera S3/U3 Light",
            kategori = "Svinghjul",
            maksAntall = 2,
        ),
        Del(
            "196602",
            "Dekk Schwalbe One 24\"x1",
            levArtNr = "1000053",
            kategori = "Dekk",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/196602.jpg",
        ),
        Del(
            "202326",
            "Dekk Schwalbe RightRun 26\"x1",
            levArtNr = "1000056",
            kategori = "Dekk",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/202326.jpg",
        ),
        Del(
            "211449",
            "Slange 24x1 bilventil",
            levArtNr = "1000005",
            kategori = "Slange",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/211449.jpg",
        ),
        Del(
            "232810",
            "Svinghjul 90 mm",
            levArtNr = "2002010",
            kategori = "Svinghjul",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/232810.jpg",
        ),
        Del(
            "278033",
            "Dekk Schwalbe RightRun 25\"x1",
            kategori = "Dekk",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/278033.png",
        ),

        // TEST
        Del(
            "196027",
            "Batteri MK 97Ah",
            levArtNr = "602293-99-0",
            kategori = "Batteri",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/196027.png",
        ),
    ),
    "X850" to listOf(
        Del(
            "157312",
            "Hjul bak",
            kategori = "Hjul",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/157312.png",
        ),
        Del(
            "157314",
            "Hjul foran",
            kategori = "Hjul",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/157314.png",
        ),
        Del(
            "196027",
            "Batteri MK 97Ah",
            levArtNr = "602293-99-0",
            kategori = "Batteri",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/196027.png",
        ),
        Del(
            "309225",
            "Batterilader 10Ah",
            levArtNr = "1836502",
            kategori = "Lader",
            maksAntall = 2,
        ),
    ),
    "X850S" to listOf(
        Del(
            "309144",
            "Hjul foran",
            levArtNr = "1838056",
            kategori = "Hjul",
            maksAntall = 2,
            img = "https://storage.googleapis.com/hm_delbestilling_bilder/309144.png",
        ),
        Del(
            "309145",
            "Hjul bak",
            levArtNr = "1838057",
            kategori = "Hjul",
            maksAntall = 2,
        ),
        Del(
            "309225",
            "Batterilader 10Ah",
            levArtNr = "1836502",
            kategori = "Lader",
            maksAntall = 2,
        ),
    ),
)
