apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: hm-delbestilling-api-rapporter-deler-til-anmodning
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  timeZone: Europe/Oslo
  schedule: '0 1 * * 1-5' # kl 01.00 (UTC+2) man til fre
  successfulJobsHistoryLimit: 1
  ttlSecondsAfterFinished: 14400
  restartPolicy: Never
  image: {{image}}
  azure:
    application:
      enabled: true
  env:
  - name: CRONJOB_TYPE
    value: RAPPORTERINGSJOBB
  - name: DELBESTILLING_API_URL
    value: http://hm-delbestilling-api.teamdigihot.svc.cluster.local
  - name: DELBESTILLING_API_SCOPE
    value: api://prod-gcp.teamdigihot.hm-delbestilling-api/.default
  envFrom:
    - secret: hm-slack-hook
  accessPolicy:
    outbound:
      external:
        - host: hooks.slack.com
      rules:
        - application: hm-delbestilling-api
        - application: logging
          namespace: nais-system
