---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-delbestilling-api
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isalive
  readiness:
    path: /isready
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 512Mi
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: hm-delbestilling
        - application: hm-soknadsbehandling
    outbound:
      rules:
        - application: hm-oebs-api-proxy
        - application: hm-roller
        - application: digihot-oppslag
      external:
        - host: kafka-schema-registry.nais-q.adeo.no
        - host: hm-oebs-api-proxy.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - name: hm-delbestilling-api-db-dev-v1
        type: POSTGRES_14
        tier: db-f1-micro
        diskType: SSD
        highAvailability: false
        diskSize: 10
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: hm-delbestilling-api-db-dev-v1
            envVarPrefix: DB
        cascadingDelete: false
  secureLogs:
    enabled: true
  env:
    - name: OEBS_API_URL
      value: https://hm-oebs-api-proxy.dev-fss-pub.nais.io
    - name: OEBS_API_SCOPE
      value: api://dev-fss.teamdigihot.hm-oebs-api-proxy/.default
    - name: ROLLER_API_URL
      value: http://hm-roller.teamdigihot.svc.cluster.local
    - name: ROLLER_API_SCOPE
      value: dev-gcp:teamdigihot:hm-roller
    - name: PDL_GRAPHQL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_API_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: OPPSLAG_API_URL
      value: http://digihot-oppslag.teamdigihot.svc.cluster.local