---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-delbestilling-api
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 2
  liveness:
    path: /isalive
    initialDelay: 40
  readiness:
    path: /isready
    initialDelay: 40
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 512Mi
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true # for å generere Azure-token
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  leaderElection: true
  ingresses:
    - https://hjelpemidler.ekstern.dev.nav.no/api/oppslag-ekstern-dev
  accessPolicy:
    inbound:
      rules:
        - application: hm-delbestilling
        - application: hm-delbestilling-ekstern
        - application: hm-delbestilling-prod-mirror
        - application: hm-soknadsbehandling
        - application: tokenx-token-generator
          namespace: nais
          cluster: dev-gcp
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
    outbound:
      rules:
        - application: hm-oebs-api-proxy
        - application: hm-roller
        - application: digihot-oppslag
        - application: hm-grunndata-search
        - application: logging
          namespace: nais-system
      external:
        - host: kafka-schema-registry.nais-q.adeo.no
        - host: hm-oebs-api-proxy.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
        - host: hooks.slack.com
        - host: finnhjelpemiddel.nav.no
        - host: login.microsoftonline.com
        - host: graph.microsoft.com

  kafka:
    pool: nav-dev
  envFrom:
    - secret: hm-slack-hook
  gcp:
    sqlInstances:
      - name: hm-delbestilling-api-db-dev-v1
        type: POSTGRES_14
        tier: db-f1-micro
        diskType: SSD
        highAvailability: false
        diskSize: 10
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: hm-delbestilling-api-db-dev-v1
            envVarPrefix: DB
        cascadingDelete: false
  env:
    - name: OEBS_API_URL
      value: https://hm-oebs-api-proxy.dev-fss-pub.nais.io
    - name: OEBS_API_SCOPE
      value: api://dev-fss.teamdigihot.hm-oebs-api-proxy/.default
    - name: ROLLER_API_URL
      value: http://hm-roller.teamdigihot.svc.cluster.local
    - name: ROLLER_API_SCOPE
      value: dev-gcp:teamdigihot:hm-roller
    - name: PDL_GRAPHQL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_API_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: OPPSLAG_API_URL
      value: http://digihot-oppslag.teamdigihot.svc.cluster.local
    - name: GRUNNDATA_API_URL
      value: https://finnhjelpemiddel.nav.no
    - name: NORG_API_URL
      value: https://norg2.dev-fss-pub.nais.io/norg2/api/v1
    - name: EPOST_AVSENDER
      value: "digitalisering.av.hjelpemidler.og.tilrettelegging@trygdeetaten.no"