schema: pdl-api-schema.graphql
extensions:
  endpoints:
    PDL GraphQL Endpoint:
      url: https://pdl-api.dev-fss-pub.nais.io/graphql
      headers:
        user-agent: hm-delbestilling-api
      introspect: false
