name: build-deploy-dev
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - main
      - brukerpass-statistikk

jobs:
  call-workflow:
    uses: navikt/digihot-deploy/.github/workflows/deploy-dev.yml@v3
    with:
      NAIS_RESOURCE: ".nais/nais-dev.yaml"
      NAIS_VARS: ".nais/vars.yaml"
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}