name: job-rapporter-manglende-deler
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - main
      - rapporter-manglende-deler
jobs:
  run-job-rapporter-manglende-deler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: get release tag
        run: |
          APPLICATION=$(echo $GITHUB_REPOSITORY | cut -d "/" -f 2)
          IMAGE=ghcr.io/$GITHUB_REPOSITORY/$APPLICATION:${{ inputs.imageVersion }}
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
          echo $IMAGE

      - uses: nais/deploy/actions/deploy@v1
        name: run job rapporter-manglende-deler on dev-gcp
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-job-rapporter-manglende-deler.yml
          IMAGE: ${{steps.docker-build-push.outputs.image}}